doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        #        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppAttributes:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity/Attributes'
                prefix: 'App\Entity\Attributes'
                alias: AppAttributes
            AppAnnotations:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Annotations'
                prefix: 'App\Entity\Annotations'
                alias: AppAnnotations
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
        dql:
            string-functions:
                binary: DoctrineExtensions\Query\Mysql\Binary

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
