monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        deprecation:
            type: rotating_file
            channels: [ deprecation ]
            path: "%kernel.logs_dir%/deprecations/%kernel.environment%.deprecations.log"
            max_files: 30

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event" ]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

when@test:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/relay.log'
                channels: [ 'relay' ]

when@prod:
    monolog:
        channels:
            - login
            - personal_data
            - user
            - relay
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            activity:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/login.log'
                channels: [ 'login' ]
            personal_data:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/personal_data.log'
                channels: [ 'personal_data' ]
            user:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/user.log'
                channels: [ 'user' ]
            relay:
                level: debug
                type: stream
                path: '%kernel.logs_dir%/activity/relay.log'
                channels: [ 'relay' ]