twig:
    #    default_path: '%kernel.project_dir%/templates'
    #    debug: '%kernel.debug%'
    #    strict_variables: '%kernel.debug%'
    #    exception_controller: null

    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        googleSiteVerification: '%env(GOOGLE_SITE_VERIFICATION)%'
        appEnv: '%env(APP_ENV)%'
        crispWebsiteId: '%env(CRISP_WEBSITE_ID)%'
    form_themes:
        - '@VichUploader/Form/fields.html.twig'
        - 'form/fields.html.twig'
        - 'bootstrap_3_layout.html.twig'
