monolog:
    channels:
        - login
        - personal_data
        - user
        - relay
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        activity:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/activity/login.log'
            channels: [ 'login' ]
        personal_data:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/activity/personal_data.log'
            channels: [ 'personal_data' ]
        user:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/activity/user.log'
            channels: [ 'user' ]
        relay:
            level: debug
            type: stream
            path: '%kernel.logs_dir%/activity/relay.log'
            channels: [ 'relay' ]
