App\Entity\ClientCentre:
  type: entity
  repositoryClass: App\Repository\ClientCentreRepository
  manyToOne:
    entity:
      targetEntity: App\Entity\Centre
      inversedBy: externalLinks
  lifecycleCallbacks: {  }
